### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by fmc088** [minimal-manifest-twrp/platform_manifest_twrp_omni#36]
. build/envsetup.sh; lunch omni_<device>-eng; mka recoveryimage
error:
*******:~/work/newDisk/twrp_source$ mka recoveryimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=8.1.0
TARGET_PRODUCT=omni_emulator
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86
TARGET_ARCH_VARIANT=x86
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-135-generic-x86_64-with-Ubuntu-14.04-trusty
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=OPM8.181105.002
OUT_DIR=/home/fmc/work/newDisk/twrp_source/out
============================================
ninja: no work to do.
[1/1] /home/fmc/work/newDisk/twrp_source/out/soong/.bootstrap/bin/soong_build /home/fmc/work/newDisk/twrp_source/out/soong/build.ninja
open : no such file or directory
bootable/recovery/gui/Android.mk was modified, regenerating...
[3/190] including ./bootable/recovery/Android.mk ...
/bin/bash: 第 0 行: test: -ge: 需要一元表达式
bootable/recovery/gui/Android.mk:170: warning: 
****************************************************************************
  Could not find ui.xml for TW_THEME: 
  Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT to automatically select
  an appropriate theme, or set TW_THEME to one of the following:
    landscape_hdpi landscape_mdpi portrait_hdpi portrait_mdpi watch_mdpi
****************************************************************************
bootable/recovery/gui/Android.mk:171: error: Theme selection failed; exiting.
11:13:25 ckati failed with: exit status 1

#### failed to build some targets (6 seconds) ####

**Comment by CaptainThrowback** [comment]
Lunch for your device first. This is not a manifest issue.

**Comment by LeeMenHin** [comment]
i also lunch for my device get this issues also

**Comment by qiurui144** [comment]
can Set TARGET_SCREEN_WIDTH and TARGET_SCREEN_HEIGHT in boardconfig.mk

**Comment by Johx22** [comment]
I am also getting this problem. TW_THEME is clearly specified in my BoardConfig.mk. Any fix??

**Comment by tjhexf** [comment]
> I am also getting this problem. TW_THEME is clearly specified in my BoardConfig.mk. Any fix??

I'm having the same damn problem.
Did anyone figure this out? It's set, and i've lunched for my device. Yet it still tells me it's not defined.

**Comment by mathew2214** [comment]
i am also having this issue

**Comment by CaptainThrowback** [comment]
If you're having this issue, then you're doing it wrong, plain and simple.

**Comment by mathew2214** [comment]
what could i be doing so wrong to cause the boardconfig.mk file to not be read correctly?

**Comment by CaptainThrowback** [comment]
> what could i be doing so wrong to cause the boardconfig.mk file to not be read correctly?

I have no idea. You have provided no logs, device tree link, or anything for reference, so I would have to guess, and I'm not going to do that.

The initial post in this topic doesn't even include the device name in the lunch command, so your issue could literally be anything, as I would never have guessed that would be the error for which this issue was created.

**Comment by nova2moon** [comment]
Made this "discovery" today, while building for new device, it dawned / occurred, that the way the build framework is designed, "lunch" sets up the TARGET_PRODUCT, and at a later time, in same context/shell, the 'mka' (m) must run to pickup that TARGET_PRODUCT.  If the above is not kept, the cryptic TW_THEME not defined error appears, even though  it IS defined in the Boardconfig.mk :) since 'm' (mka) picks up some default "product" and no ui.xml is found.

Examples of it failing would be:
(lunch twrp_ping-eng) 
mka recoveryimage
Here, the lunch, will succeed, and set up TARGET_PRODUCT, however, the () place all that in a separate SHELL, as such, the subsequent mka FAILS with the TW_THEME not defined and ui.xml not found error.

Looking at Original post, in fact, all information is provided and enough to conclude this issue is same.. Notice the commands user is running:

. build/envsetup.sh; lunch omni_-eng; mka recoveryimage

notice the "lunch" does not have a DEVICE NAME listed, at ALL?  it is probably omni-${device}-env - and they have forgotten to set device=something, as such, no TARGET_PRODUCT is setup, and as such, the mka fails with that error.

Notice the "TARGET_PRODUCT=omni_emulator" produced by dumpvars shows that is NOT the "device" the user is building for.

Took me about a day to figure that out, so thought to share...
