### ISSUE TITLE
fatal: couldn't find remote ref refs/heads/twrp-10.0

### ISSUE THREAD

**Issue by wmhaganjr1013** [minimal-manifest-twrp/platform_manifest_twrp_omni#63]
I am a noob but have never had this problem 
fatal: couldn't find remote ref refs/heads/twrp-10.0
how do i fix this please

**Comment by MartinX3** [comment]
Wrong branch name :P

**Comment by wmhaganjr1013** [comment]
as per directions i input ,,  repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0 
after i input this i get  fatal: couldn't find remote ref refs/heads/twrp-10.0 
can u please help with what i am doing wrong please

**Comment by theimpulson** [comment]
@wmhaganjr1013 use the following command to initialize the repo:
`repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0-WIP`

You can notice the branch name in README and repo is different which is why this error happens. Use the branch name to initalize the repo next time.

**Comment by wmhaganjr1013** [comment]
thankyou Sir i missed it
